- name: Download wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /etc/foo.conf
    dest: /tmp 

    - name: Extract wordpress
    ansible.builtin.unarchive:
      src: /tmp/wordpress-6.7.1.tar.gz
      dest: /tmp
      remote_src: yes

      - name: Copy file with owner and permissions
        ansible.builtin.copy:
        src: /tmp/wordpress/.
        dest: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'

        - name: Change file ownership, group and permissions
          ansible.builtin.file:
            path: /var/www/html/index.html
            state: absent 